# FROM quay.io/astronomer/ap-airflow:1.10.12-buster-onbuild
# FROM quay.io/astronomer/ap-airflow:2.3.4-7-onbuild

FROM quay.io/astronomer/astro-runtime:5.5.0


RUN pip install --user dist/revisions_toolkit-0.1-py3-none-any.whl
