### Parameters for the project. Read the documentation to understand where things are and why.


# THIS MATCHES THE FILENAMES IN THE DOWNLOADED ZIP FOLDERS WE WANT TO PROCESS
headline_qgdp_filename_list: 
  - "ABMI - Quarterly GDP at Market Prices"
headline_qgdp_writepath: "data/02_intermediate/headline/"

# THIS MATCHES THE FILENAMES IN THE DOWNLOADED ZIP FOLDERS WE WANT TO PROCESS
headline_mgdp_filename_list:
  - "mgdp revision triangle (m on m)"
  - "mgdp revision triangle (3m on 3m)"
headline_mgdp_writepath: "data/02_intermediate/headline/"

# THIS MATCHES THE FILENAMES IN THE DOWNLOADED ZIP FOLDERS WE WANT TO PROCESS
expenditure_qgdp_filename_list:
  - "ABJR - Household Final Consumption"
  - "BQKO - Imports of Goods"
  - "BQKQ - Exports of Goods"
  - "CAFU - Change in Inventories"
  - "HAYO - Non-Profit"
  - "IKBE - Export of Services"
  - "IKBF - Imports of Services"
  - "IKBK - Total Imports"
  - "NMRY - General Government"
  - "NPQT - Gross Fixed Capital"
expenditure_writepath: "data/02_intermediate/expenditure/"

# MATCHES THE FILENAME OF THE DOWNLOADED XL FILE
deflator_qgdp_filename_list:
  - ybgbgdpimplieddeflator.xlsx
deflator_writepath: "data/02_intermediate/headline/"

# MATCHES THE FILENAME OF THE DOWNLOADED XL FILE
income_qgdp_filename_list:
  - "CAEQ - Public corporations gross operating surplus.xlsx"
  - "CAER - Private non-financial corporations gross operating surplus.xlsx"
  - "CGBX - Other Income.xlsx"
  - "CMVL - Taxes less subsidies.xlsx"
  - "DTWM - Compensation of employees.xlsx"
  - "NHCZ - Financial corporations gross operating surplus.xlsx"
income_writepath: "data/02_intermediate/income/"

investment_qgdp_filename_list:
  - "dataset5rftrt.xls"
investment_writepath: "data/02_intermediate/headline/"